name: The Sound Off
favicon: null
layout_spectrum: 0.79284
typography_spectrum: 0.28297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030200'
    - '#ffffff'
    - '#5f451c'
    - '#d5a86b'
    - '#926b38'
  brandStrength: 0.7140841619111598
  lightness: 0.5230717435479164
  saturation: 0.28076555393636227
  rhythmicContrast: 0.5047440764028579
purpose: []
