name: The Sound Off
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#1d974b'
    - '#7bc49c'
    - '#8b8a8a'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
