name: The Sound Off
favicon: null
layout_spectrum: 1
typography_spectrum: 0.112766
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Sound Off
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#231F20'
    - '#0F9848'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
